### ISSUE TITLE
Error failed to register events for class

### ISSUE THREAD

**Issue by Bloodlex** [LittleBigBug/acoworth#12] opened 2020-08-02 16:21 UTC
[18:20:03 ERROR]: [AcoWorth] Plugin AcoWorth v1.6 has failed to register events for class net.yasfu.acoworth.ShopListeners.AuctionHouseListener because me/badbones69/crazyauctions/api/events/AuctionWinBidEvent does not exist.

Server version: **Paper-131 (MC: 1.16.1)**

Occured during server startup.

**Comment by LittleBigBug** [comment] 2020-08-02 23:58
Hi, this is a duplicate of #10 
I've been busy.. sorry. I will look into this soon.

**Comment by Bloodlex** [comment] 2020-08-03 03:37
Okay, thanks, looking forward to it 👍

**Comment by LittleBigBug** [comment] 2020-10-09 01:29
fixed in f1af607
Duplicate of #10

**Closed by LittleBigBug** 2020-10-09 01:29 UTC
Labels: bug, duplicate
